CREATE TABLE IF NOT EXISTS cat (
    `properties_key` VARCHAR(21) CHARACTER SET utf8,
    `properties_properties_name` VARCHAR(30) CHARACTER SET utf8,
    `properties_properties_category` VARCHAR(21) CHARACTER SET utf8
);
INSERT INTO cat VALUES
    ('aps','All Departments','aps'),
    ('audible','Audible Books & Originals','audible'),
    ('alexa-skills','Alexa Skills','alexa-skills'),
    ('amazon-devices','Amazon Devices','amazon-devices'),
    ('amazonfresh','Amazon Fresh','amazonfresh'),
    ('warehouse-deals','Amazon Warehouse','warehouse-deals'),
    ('appliances','Appliances','appliances'),
    ('mobile-apps','Apps & Games','mobile-apps'),
    ('arts-crafts','Arts, Crafts & Sewing','arts-crafts'),
    ('automotive','Automotive Parts & Accessories','automotive'),
    ('baby-products','Baby','baby-products'),
    ('beauty','Beauty & Personal Care','beauty'),
    ('stripbooks','Books','stripbooks'),
    ('popular','CDs & Vinyl','popular'),
    ('mobile','Cell Phones & Accessories','mobile'),
    ('fashion','Clothing, Shoes & Jewelry','fashion'),
    ('fashion-womens','   Women','fashion-womens'),
    ('fashion-mens','   Men','fashion-mens'),
    ('fashion-girls','   Girls','fashion-girls'),
    ('fashion-boys','   Boys','fashion-boys'),
    ('fashion-baby','   Baby','fashion-baby'),
    ('under-ten-dollars','Under $10','under-ten-dollars'),
    ('pantry','Amazon Pantry','pantry'),
    ('collectibles','Collectibles & Fine Art','collectibles'),
    ('computers','Computers','computers'),
    ('courses','Courses','courses'),
    ('financial','Credit and Payment Cards','financial'),
    ('edu-alt-content','Digital Educational Resources','edu-alt-content'),
    ('digital-music','Digital Music','digital-music'),
    ('electronics','Electronics','electronics'),
    ('lawngarden','Garden & Outdoor','lawngarden'),
    ('gift-cards','Gift Cards','gift-cards'),
    ('grocery','Grocery & Gourmet Food','grocery'),
    ('handmade','Handmade','handmade'),
    ('hpc','Health, Household & Baby Care','hpc'),
    ('local-services','Home & Business Services','local-services'),
    ('garden','Home & Kitchen','garden'),
    ('industrial','Industrial & Scientific','industrial'),
    ('prime-exclusive','Just for Prime','prime-exclusive'),
    ('digital-text','Kindle Store','digital-text'),
    ('fashion-luggage','Luggage & Travel Gear','fashion-luggage'),
    ('magazines','Magazine Subscriptions','magazines'),
    ('movies-tv','Movies & TV','movies-tv'),
    ('mi','Musical Instruments','mi'),
    ('office-products','Office Products','office-products'),
    ('pets','Pet Supplies','pets'),
    ('luxury-beauty','Premium Beauty','luxury-beauty'),
    ('instant-video','Prime Video','instant-video'),
    ('smart-home','Smart Home','smart-home'),
    ('software','Software','software'),
    ('sporting','Sports & Outdoors','sporting'),
    ('subscribe-with-amazon','Subscription Boxes','subscribe-with-amazon'),
    ('tools','Tools & Home Improvement','tools'),
    ('toys-and-games','Toys & Games','toys-and-games'),
    ('vehicles','Vehicles','vehicles'),
    ('videogames','Video Games','videogames'),
    ('wholefoods','Whole Foods Market','wholefoods');
